# Settings
baseurl = "http://example.org/"
languageCode = "en-us"
title = "Shoto Creative"
theme = "phugo"
googleAnalytics = "UA-XXXXXXX-Y"

[params]

    # Meta
    description = "Shoto Creative - Greater Toronto Area Creative Studio"
    author = "aerohub"
    keywords = "photography, videography, video, photo, photogallery"
    
    # Headerbar links
    # Do not put here too many links,
    # it will break mobile appearance

    [[params.header.links]]
    name = "About & Contact"
    url = "#footer"
    icon = "fa-info-circle"    
    
    # Footer panel
    
    [params.footer.paragraph]
    headline = "We're Shoto Creative"
    text = "We're event photographers located in the GTA."
    
    [params.footer.social]
    headline = "Follow Us"

    # [[params.footer.social.links]]
    # label = "Facebook"
    # url = "#"
    # icon = "fa-facebook"

    [[params.footer.social.links]]
    label = "Instagram"
    url = "https://www.instagram.com/shoto.ca/"
    icon = "fa-instagram"
    
    # Contact form
    
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'realEmail' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    
    [params.footer.contact]
    hide = false # Set this to true if you don't want to have a contact form on your site
    realEmail = "social@shoto.ca"
    headline = "Get in touch"
    buttonText = "Send"
    resetText = "Reset"
    
    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Name *"
    warning = "Please, enter your name"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Please, enter your email."

    [params.footer.contact.message]
    text = "Message *"
    warning = "Please, enter your message"
    
    # Copyright
    [params.footer.copyright]
    name = "Shoto Creative"